### ISSUE TITLE
Is the code published now complete？

### ISSUE THREAD

**Issue by tg-Flipped** [ucas-vg/Effective-Fusion-Factor#2]
Hi~, authors, I have two questions about this code. 
Firstly, is the code published now complete? I can not find some functions or python file.
Secondly, in "train_net.py", line 30, the "build_detection_model" function needs two arguments. One is cfg and  another is fusion_factors. But there is only one cfg argument in the code. I have some doubts about this.
 Looking forward to your early reply.

**Comment by Muqianli** [comment]
> Hi~, authors, I have two questions about this code.
> Firstly, is the code published now complete? I can not find some functions or python file.
> Secondly, in "train_net.py", line 30, the "build_detection_model" function needs two arguments. One is cfg and another is fusion_factors. But there is only one cfg argument in the code. I have some doubts about this.
> Looking forward to your early reply.

Thank you for your question! We have resubmitted the code. Please use train_test_net.py for training and testing.

**Comment by tg-Flipped** [comment]
> > Hi~, authors, I have two questions about this code.
> > Firstly, is the code published now complete? I can not find some functions or python file.
> > Secondly, in "train_net.py", line 30, the "build_detection_model" function needs two arguments. One is cfg and another is fusion_factors. But there is only one cfg argument in the code. I have some doubts about this.
> > Looking forward to your early reply.
> 
> Thank you for your question! We have resubmitted the code. Please use train_test_net.py for training and testing.

Thanks for your reply.
